# Generated by Django 4.2.5 on 2023-10-04 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('rateTables', '0005_alter_installment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_interest', models.IntegerField(null=True)),
                ('installment_interest_value', models.FloatField()),
                ('comission', models.FloatField()),
                ('comission_value', models.FloatField()),
                ('installment_value', models.FloatField()),
                ('card_number', models.CharField(max_length=16, null=True)),
                ('desired_value', models.FloatField()),
                ('total_loan', models.FloatField()),
                ('contract_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='automatic', max_length=10)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to='clients.client')),
                ('installment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitations', to='rateTables.installment')),
                ('rate_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitations', to='rateTables.ratetable')),
            ],
        ),
    ]
