# Generated by Django 4.2.5 on 2023-10-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='comission',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='comission_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='desired_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='installment_interest_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='installment_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='total_loan',
            field=models.FloatField(null=True),
        ),
    ]
