# Generated by Django 4.2.5 on 2023-10-03 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('installment_interest', models.IntegerField()),
                ('rate_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='rateTables.ratetable')),
            ],
        ),
    ]
