# Generated by Django 4.2.5 on 2023-10-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateTables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='comission',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
