# Generated by Django 4.2.5 on 2023-10-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateTables', '0002_installment_comission'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratetable',
            name='name',
            field=models.CharField(default=None, max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
