# Generated by Django 4.2.5 on 2023-10-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateTables', '0004_alter_installment_comission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['installment_number']},
        ),
    ]
