# Generated by Django 4.2.5 on 2023-10-03 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_label', models.CharField(max_length=50)),
                ('account_type_label', models.CharField(choices=[('current account', 'Current Account'), ('savings account', 'Savings Account')], default='current account', max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
