# Generated by Django 4.2.5 on 2023-10-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_card_back_image_alter_card_front_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='back_image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='front_image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='selfie_image',
            field=models.URLField(),
        ),
    ]
